<?php
/*
Plugin Name: Advanced Cache Pro
Plugin URI: https://example.com/
Description: File-based page cache with improved minify + gzip serving. Generated by ChatGPT.
Version: 1.3
Author: ChatGPT
License: GPLv2 or later
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Advanced_Cache_Pro {
    private static $instance = null;
    private $options = array();
    private $cache_dir;

    public static function instance() {
        if ( self::$instance === null ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        $this->cache_dir = WP_CONTENT_DIR . '/advanced-cache-pro-cache';
        $this->options = get_option( 'acp_options', array(
            'enabled'       => 1,
            'ttl'           => 3600,
            'exclude'       => '',
            'minify_html'   => 1,
            'minify_css'    => 1,
            'minify_js'     => 1,
            'gzip'          => 1,
            'cache_control' => 'public, max-age=%d',
        ) );

        if ( ! file_exists( $this->cache_dir ) ) {
            wp_mkdir_p( $this->cache_dir );
        }

        add_action( 'template_redirect', array( $this, 'maybe_serve_cache' ), 0 );
        add_action( 'shutdown', array( $this, 'maybe_save_cache' ), 0 );

        add_action( 'save_post', array( $this, 'purge_cache_on_post_change' ), 10, 3 );
        add_action( 'deleted_post', array( $this, 'purge_cache_on_post_change' ) );
        add_action( 'edit_post', array( $this, 'purge_cache_on_post_change' ) );
        add_action( 'wp_trash_post', array( $this, 'purge_cache_on_post_change' ) );
        add_action( 'comment_post', array( $this, 'purge_cache_on_post_change' ) );
        add_action( 'transition_comment_status', array( $this, 'purge_cache_on_post_change' ), 10, 3 );

        add_action( 'admin_menu', array( $this, 'admin_menu' ) );
        add_action( 'admin_init', array( $this, 'register_settings' ) );
        add_action( 'admin_bar_menu', array( $this, 'admin_bar_purge_link' ), 100 );
        add_action( 'admin_post_acp_purge_url', array( $this, 'handle_purge_request' ) );
        add_action( 'admin_post_acp_purge_all', array( $this, 'handle_purge_all_request' ) );

        add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), array( $this, 'plugin_action_links' ) );
    }

    private function is_enabled() {
        return ! empty( $this->options['enabled'] );
    }

    private function is_cacheable() {
        if ( ! $this->is_enabled() ) return false;
        if ( is_user_logged_in() ) return false;
        if ( $_SERVER['REQUEST_METHOD'] !== 'GET' ) return false;
        if ( is_admin() ) return false;
        if ( is_feed() || is_preview() ) return false;

        $exclude = isset( $this->options['exclude'] ) ? $this->options['exclude'] : '';
        if ( ! empty( $exclude ) ) {
            $uri = isset( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '/';
            $lines = preg_split( '/\r\n|\r|\n/', $exclude );
            foreach ( $lines as $pattern ) {
                $pattern = trim( $pattern );
                if ( $pattern === '' ) continue;
                if ( strpos( $uri, $pattern ) !== false ) return false;
            }
        }
        return true;
    }

    private function cache_file_path_for_uri( $uri ) {
        $key = md5( home_url( $uri ) );
        return trailingslashit( $this->cache_dir ) . $key . '.html';
    }

    private function cache_file_path() {
        $uri = isset( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '/';
        return $this->cache_file_path_for_uri( $uri );
    }

    public function maybe_serve_cache() {
        if ( ! $this->is_cacheable() ) {
            if ( ! is_admin() && ! is_user_logged_in() && $_SERVER['REQUEST_METHOD'] === 'GET' ) ob_start();
            return;
        }

        $file = $this->cache_file_path();
        $ttl = isset( $this->options['ttl'] ) ? intval( $this->options['ttl'] ) : 3600;
        if ( file_exists( $file ) && ( time() - filemtime( $file ) ) < $ttl ) {
            // Serve gzipped if client accepts and gz file exists
            $accept = isset( $_SERVER['HTTP_ACCEPT_ENCODING'] ) ? $_SERVER['HTTP_ACCEPT_ENCODING'] : '';
            $gz = $file . '.gz';
            header( 'X-Advanced-Cache-Pro: HIT' );
            header( 'Content-Type: text/html; charset=UTF-8' );
            header( sprintf( 'Cache-Control: ' . $this->options['cache_control'], $ttl ) );
            if ( strpos( $accept, 'gzip' ) !== false && file_exists( $gz ) ) {
                header( 'Content-Encoding: gzip' );
                readfile( $gz );
                exit;
            } else {
                readfile( $file );
                exit;
            }
        } elseif ( file_exists( $file ) ) {
            @unlink( $file );
            @unlink( $file . '.gz' );
        }

        ob_start();
    }

    private function protect_blocks( $content ) {
        // Temporarily replace contents of pre, code, textarea, script and style to avoid accidental minification
        $blocks = array();
        $i = 0;
        $pattern = '#<(pre|code|textarea|script|style)\b[^>]*>(.*?)</\1>#is';
        $content = preg_replace_callback( $pattern, function( $m ) use ( &$blocks, &$i ) {
            $placeholder = "###ACP_BLOCK_{$i}###";
            $blocks[$placeholder] = $m[0]; // store full block (including tags)
            $i++;
            return $placeholder;
        }, $content );
        return array( 'content' => $content, 'blocks' => $blocks );
    }

    private function restore_blocks( $content, $blocks ) {
        if ( empty( $blocks ) ) return $content;
        return str_replace( array_keys( $blocks ), array_values( $blocks ), $content );
    }

    private function minify_html_content( $content ) {
        if ( empty( $content ) ) return $content;

        $protected = $this->protect_blocks( $content );
        $content = $protected['content'];
        $blocks = $protected['blocks'];

        // Remove HTML comments except IE conditionals
        $content = preg_replace( '/<!--(?!\[if).*?-->/s', '', $content );
        // Remove whitespace between tags
        $content = preg_replace( '/>\s+</', '><', $content );
        // Collapse multiple spaces into one
        $content = preg_replace( '/\s{2,}/', ' ', $content );
        $content = trim( $content );

        // If inline CSS minify enabled, process style blocks placeholders now
        if ( ! empty( $this->options['minify_css'] ) ) {
            foreach ( $blocks as $ph => $orig ) {
                if ( stripos( $orig, '<style' ) === 0 ) {
                    // minify CSS inside
                    $css = preg_replace( '#^<style[^>]*>|</style>$#is', '', $orig );
                    $css = preg_replace( '#/\*.*?\*/#s', '', $css );
                    $css = preg_replace( '/\s+/', ' ', $css );
                    $css = trim( $css );
                    $blocks[$ph] = '<style>' . $css . '</style>';
                }
            }
        }

        // If inline JS minify enabled, process script blocks placeholders now
        if ( ! empty( $this->options['minify_js'] ) ) {
            foreach ( $blocks as $ph => $orig ) {
                if ( stripos( $orig, '<script' ) === 0 ) {
                    $js = preg_replace( '#^<script\b[^>]*>|</script>$#is', '', $orig );
                    // remove block comments
                    $js = preg_replace( '#/\*.*?\*/#s', '', $js );
                    // remove line comments
                    $js = preg_replace( '/(^|\s)\/\/[^\n\r]*/', '', $js );
                    $js = preg_replace( '/\s+/', ' ', $js );
                    $js = trim( $js );
                    $blocks[$ph] = '<script>' . $js . '</script>';
                }
            }
        }

        // Restore protected blocks
        $content = $this->restore_blocks( $content, $blocks );
        return $content;
    }

    public function maybe_save_cache() {
        if ( ! $this->is_cacheable() ) {
            if ( ob_get_length() !== false ) ob_end_flush();
            return;
        }

        $status = http_response_code();
        if ( $status !== null && intval( $status ) !== 200 ) {
            if ( ob_get_length() !== false ) ob_end_flush();
            return;
        }

        if ( ob_get_length() === false ) return;
        $content = ob_get_clean();
        if ( $content === '' ) {
            echo $content;
            return;
        }

        // Minify HTML and inline assets
        if ( ! empty( $this->options['minify_html'] ) ) {
            $content = $this->minify_html_content( $content );
        }

        $file = $this->cache_file_path();
        if ( ! file_exists( $this->cache_dir ) ) wp_mkdir_p( $this->cache_dir );
        $tmp = $file . '.tmp';
        file_put_contents( $tmp, $content );
        @chmod( $tmp, 0644 );
        rename( $tmp, $file );

        // Create gzipped version if enabled
        if ( ! empty( $this->options['gzip'] ) ) {
            $gz = $file . '.gz';
            file_put_contents( $gz, gzencode( $content, 9 ) );
            @chmod( $gz, 0644 );
        }

        header( 'X-Advanced-Cache-Pro: MISS' );
        echo $content;
    }

    public function purge_cache_on_post_change( $post_id = 0 ) {
        if ( $post_id ) {
            $permalink = get_permalink( $post_id );
            if ( $permalink ) $this->purge_url( $permalink );
        }
        $this->purge_url( home_url( '/' ) );
    }

    public function purge_all() {
        $files = glob( trailingslashit( $this->cache_dir ) . '*.html' );
        if ( $files ) {
            foreach ( $files as $f ) {
                @unlink( $f );
                @unlink( $f . '.gz' );
            }
        }
    }

    public function purge_url( $url ) {
        if ( empty( $url ) ) return;
        $parts = parse_url( $url );
        $path = isset( $parts['path'] ) ? $parts['path'] : '/';
        $query = isset( $parts['query'] ) ? '?' . $parts['query'] : '';
        $uri = $path . $query;
        $file = $this->cache_file_path_for_uri( $uri );
        if ( file_exists( $file ) ) @unlink( $file );
        if ( file_exists( $file . '.gz' ) ) @unlink( $file . '.gz' );
    }

    public function plugin_action_links( $links ) {
        $settings_link = '<a href="' . esc_url( admin_url( 'options-general.php?page=advanced-cache-pro' ) ) . '">Settings</a>';
        $nonce = wp_create_nonce( 'acp_tools' );
        $purge_link = '<a href="' . esc_url( admin_url( 'admin-post.php?action=acp_purge_all&_wpnonce=' . $nonce ) ) . '">Purge Cache</a>';
        array_unshift( $links, $purge_link );
        array_unshift( $links, $settings_link );
        return $links;
    }

    public function admin_menu() {
        add_options_page( 'Advanced Cache Pro', 'Advanced Cache Pro', 'manage_options', 'advanced-cache-pro', array( $this, 'settings_page' ) );
    }

    public function register_settings() {
        register_setting( 'acp_options_group', 'acp_options', array( $this, 'sanitize_options' ) );
        add_settings_section( 'acp_main', 'Main settings', null, 'advanced-cache-pro' );
        add_settings_field( 'enabled', 'Enabled', array( $this, 'field_enabled' ), 'advanced-cache-pro', 'acp_main' );
        add_settings_field( 'ttl', 'Cache TTL (seconds)', array( $this, 'field_ttl' ), 'advanced-cache-pro', 'acp_main' );
        add_settings_field( 'exclude', 'Exclude URIs (one per line)', array( $this, 'field_exclude' ), 'advanced-cache-pro', 'acp_main' );
        add_settings_field( 'minify_css', 'Minify inline CSS', array( $this, 'field_minify_css' ), 'advanced-cache-pro', 'acp_main' );
        add_settings_field( 'minify_js', 'Minify inline JS', array( $this, 'field_minify_js' ), 'advanced-cache-pro', 'acp_main' );
        add_settings_field( 'gzip', 'Create gzipped cache file (.gz)', array( $this, 'field_gzip' ), 'advanced-cache-pro', 'acp_main' );
        add_settings_field( 'cache_control', 'Cache-Control header template', array( $this, 'field_cache_control' ), 'advanced-cache-pro', 'acp_main' );
    }

    public function sanitize_options( $input ) {
        $out = array();
        $out['enabled'] = isset( $input['enabled'] ) ? 1 : 0;
        $out['ttl'] = isset( $input['ttl'] ) ? intval( $input['ttl'] ) : 3600;
        $out['exclude'] = isset( $input['exclude'] ) ? sanitize_textarea_field( $input['exclude'] ) : '';
        $out['minify_html'] = isset( $input['minify_html'] ) ? 1 : 0;
        $out['minify_css'] = isset( $input['minify_css'] ) ? 1 : 0;
        $out['minify_js'] = isset( $input['minify_js'] ) ? 1 : 0;
        $out['gzip'] = isset( $input['gzip'] ) ? 1 : 0;
        $out['cache_control'] = isset( $input['cache_control'] ) ? sanitize_text_field( $input['cache_control'] ) : 'public, max-age=%d';
        $this->options = $out;
        return $out;
    }

    public function field_enabled() {
        $checked = ( ! empty( $this->options['enabled'] ) ) ? 'checked' : '';
        echo '<input type="checkbox" name="acp_options[enabled]" value="1" ' . $checked . ' /> Enable caching for anonymous visitors';
    }

    public function field_ttl() {
        $ttl = isset( $this->options['ttl'] ) ? intval( $this->options['ttl'] ) : 3600;
        echo '<input type="number" name="acp_options[ttl]" value="' . esc_attr( $ttl ) . '" min="60" />';
    }

    public function field_exclude() {
        $exclude = isset( $this->options['exclude'] ) ? esc_textarea( $this->options['exclude'] ) : '';
        echo '<textarea name="acp_options[exclude]" rows="6" cols="60" placeholder="/cart&#10;/checkout">' . $exclude . '</textarea>';
    }

    public function field_minify_css() {
        $checked = ( ! empty( $this->options['minify_css'] ) ) ? 'checked' : '';
        echo '<input type="checkbox" name="acp_options[minify_css]" value="1" ' . $checked . ' /> Minify inline CSS in cached pages';
    }

    public function field_minify_js() {
        $checked = ( ! empty( $this->options['minify_js'] ) ) ? 'checked' : '';
        echo '<input type="checkbox" name="acp_options[minify_js]" value="1" ' . $checked . ' /> Minify inline JS in cached pages';
    }

    public function field_gzip() {
        $checked = ( ! empty( $this->options['gzip'] ) ) ? 'checked' : '';
        echo '<input type="checkbox" name="acp_options[gzip]" value="1" ' . $checked . ' /> Create a gzipped cache file alongside the HTML cache';
    }

    public function field_cache_control() {
        $val = isset( $this->options['cache_control'] ) ? esc_attr( $this->options['cache_control'] ) : 'public, max-age=%d';
        echo '<input type="text" name="acp_options[cache_control]" value="' . $val . '" size="60" /> Use %d for TTL (e.g. "public, max-age=%d")';
    }

    public function settings_page() {
        if ( ! current_user_can( 'manage_options' ) ) return;
        ?>
        <div class="wrap">
            <h1>Advanced Cache Pro</h1>
            <form method="post" action="options.php">
                <?php settings_fields( 'acp_options_group' ); ?>
                <?php do_settings_sections( 'advanced-cache-pro' ); ?>
                <?php submit_button( 'Save Changes' ); ?>
            </form>
            <h2>Tools</h2>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
                <?php wp_nonce_field( 'acp_tools', 'acp_tools_nonce' ); ?>
                <input type="hidden" name="action" value="acp_purge_all" />
                <p><input type="submit" name="acp_purge" class="button button-secondary" value="Purge entire cache" /></p>
            </form>

            <h3>Purge specific URL</h3>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
                <?php wp_nonce_field( 'acp_tools', 'acp_tools_nonce' ); ?>
                <input type="hidden" name="action" value="acp_purge_url" />
                <p><input type="url" name="acp_purge_url" placeholder="https://example.com/path" size="60" required /> <input type="submit" class="button" value="Purge URL" /></p>
            </form>
        </div>
        <?php
    }

    public function admin_bar_purge_link( $wp_admin_bar ) {
        if ( ! current_user_can( 'manage_options' ) ) return;
        if ( is_admin() ) return;
        $current = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
        $nonce = wp_create_nonce( 'acp_tools' );
        $purge_url = admin_url( 'admin-post.php?action=acp_purge_url&acp_url=' . urlencode( $current ) . '&_wpnonce=' . $nonce );
        $wp_admin_bar->add_node( array(
            'id'    => 'acp-purge-current',
            'title' => 'Purge Cache (This Page)',
            'href'  => $purge_url,
            'meta'  => array( 'class' => 'acp-purge-link' ),
        ) );
    }

    public function handle_purge_request() {
        if ( ! current_user_can( 'manage_options' ) ) wp_die( 'Insufficient permissions' );
        if ( ! isset( $_REQUEST['_wpnonce'] ) || ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'acp_tools' ) ) wp_die( 'Invalid nonce' );
        $url = '';
        if ( isset( $_REQUEST['acp_url'] ) ) $url = esc_url_raw( $_REQUEST['acp_url'] );
        elseif ( isset( $_POST['acp_purge_url'] ) ) $url = esc_url_raw( $_POST['acp_purge_url'] );
        if ( $url ) $this->purge_url( $url );
        $redirect = wp_get_referer() ? wp_get_referer() : admin_url( 'options-general.php?page=advanced-cache-pro' );
        wp_safe_redirect( $redirect );
        exit;
    }

    public function handle_purge_all_request() {
        if ( ! current_user_can( 'manage_options' ) ) wp_die( 'Insufficient permissions' );
        if ( ! isset( $_REQUEST['_wpnonce'] ) || ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'acp_tools' ) ) wp_die( 'Invalid nonce' );
        $this->purge_all();
        $redirect = wp_get_referer() ? wp_get_referer() : admin_url( 'options-general.php?page=advanced-cache-pro' );
        wp_safe_redirect( $redirect );
        exit;
    }
}

Advanced_Cache_Pro::instance();
